use weddingplanner;


-- INSERT INTO attractions
--  VALUES (
--      NULL,
--      "venue",
--      "Seven",
--      "Shula",
--      "https://xanadu.mazaltov.walla.co.il/UploadImages/2/1475/737705_C680Cx510.jpg",
--      "Tel-Aviv",
--      4,
--      "Sarit",
--      "050-3339872",
--      "SevenTLV@gmail.com",
--      "Pellentesque tincidunt elementum dolor, id efficitur tortor. Nullam condimentum massa non lorem lobortis placerat. Vivamus quis aliquam nulla. Etiam tellus justo, vehicula sit amet aliquam id, gravida sit amet dui. Nullam aliquet et dolor eu bibendum. Nam ornare dapibus risus, quis condimentum orci cursus sed. Nullam nisl diam, cursus ut lobortis suscipit, tristique fermentum odio. Suspendisse potenti. Praesent ac arcu a tellus vulputate iaculis id quis leo."
--      );


-- INSERT INTO attractions
--  VALUES (
--      NULL,
--      "venue",
--      "Lago",
--      "Alex",
--      "https://lago.mazaltov.walla.co.il/UploadImages/Template2015/347/Intro.jpg?rev=330",
--      "Rehovot",
--      5,
--      "Eden",
--      "050-5988873",
--      "LagoEvents@gmail.com",
--      "Sed vitae aliquam sapien, quis posuere enim. Sed varius consectetur ex eu suscipit. Aenean sollicitudin, orci ac vehicula aliquet, massa massa tincidunt lectus, et malesuada tortor turpis quis magna. Phasellus finibus justo quis malesuada eleifend. Nunc molestie efficitur lorem, eget dictum sem vehicula eget. Morbi aliquam, felis nec maximus rhoncus"
--      );

--      INSERT INTO attractions
--  VALUES (
--      NULL,
--      "venue",
--      "Troya",
--      "Ronen",
--      "https://troya-garden.mazaltov.walla.co.il/UploadImages/2/1476/738442_C680Cx510.jpg",
--      "Ashdod",
--      4,
--      "Rotem",
--      "09-6845620",
--      "Troya@gmail.com",
--      "Sed vitae aliquam sapien, quis posuere enim. Sed varius consectetur ex eu suscipit. Aenean sollicitudin, orci ac vehicula aliquet, massa massa tincidunt lectus, et malesuada tortor turpis quis magna. Phasellus finibus justo quis malesuada eleifend. Nunc molestie efficitur lorem, eget dictum sem vehicula eget. Morbi aliquam, felis nec maximus rhoncus"
--      );

-- INSERT INTO attractions
--  VALUES (
--      NULL,
--      "dj",
--      "DJ Tomer Vered",
--      "DJ Tomer Vered",
--      "https://images.mitchatnim.co.il/customers/80054579/62591c0969c1489b9b69fb43b6d81f7a_33.jpg",
--      "All Country",
--      4,
--      "Tomer",
--      "050-6845620",
--      "djtomer_vered3@gmail.com",
--      "Sed vitae aliquam sapien, quis posuere enim. Sed varius consectetur ex eu suscipit. Aenean sollicitudin, orci ac vehicula aliquet, massa massa tincidunt lectus, et malesuada tortor turpis quis magna. Phasellus finibus justo quis malesuada eleifend. Nunc molestie efficitur lorem, eget dictum sem vehicula eget. Morbi aliquam, felis nec maximus rhoncus"
--      );

-- INSERT INTO attractions
--  VALUES (
--      NULL,
--      "dj",
--      "Artista",
--      "Sharon",
--      "https://artistamusic.mitchatnim.co.il/img/0572/711.jpg",
--      "All Country",
--      5,
--      "Sharon \ Dana",
--      "050-9874649",
--      "artista_music@gmail.com",
--      "Phasellus ultricies est vestibulum ante efficitur, a semper velit accumsan. Donec justo diam, dapibus eu nunc feugiat, sollicitudin rutrum felis. Suspendisse risus eros, elementum quis dolor eu, congue rutrum elit. Pellentesque non tellus eget diam tristique ultricies mattis eget odio. Vivamus maximus"
--      );

-- INSERT INTO attractions
--  VALUES (
--      NULL,
--      "dj",
--      "KETA",
--      "Ben",
--      "https://images.mitchatnim.co.il/customers/80302106/922339c553e241248971492339033d4e_33.jpg",
--      "All Country",
--      5,
--      "Ben",
--      "050-8744575",
--      "keta_productions@gmail.com",
--      "Fusce ornare suscipit cursus. Vestibulum ligula nunc, consectetur sit amet ex id, fermentum tincidunt ante. Suspendisse sed elit enim. Vestibulum ex nulla, faucibus a commodo at, dapibus quis orci."
--      );

--  INSERT INTO attractions
--  VALUES (
--      NULL,
--      "photographer",
--      "Studio Eyal",
--      "Eyal",
--      "https://images.mitchatnim.co.il/customers/80190993/f3ed1519596f4c0c93fc00b02fc260a3_33.jpg",
--      "All Country",
--      5,
--      "Dana",
--      "050-7766679",
--      "studio_eyal@gmail.com",
--      "Fusce ornare suscipit cursus. Vestibulum ligula nunc, consectetur sit amet ex id, fermentum tincidunt ante. Suspendisse sed elit enim. Vestibulum ex nulla, faucibus a commodo at, dapibus quis orci."
--      );

--       INSERT INTO attractions
--  VALUES (
--      NULL,
--      "photographer",
--      "PhotoShoot",
--      "Ben",
--      "https://images.mitchatnim.co.il/customers/80137929/8622d97ed31b4a87b90d00492de1b018_33.jpg",
--      "All Country",
--      4.7,
--      "Ben",
--      "050-7666484",
--      "BenPhotography@gmail.com",
--      "malesuada tortor turpis quis magna. Phasellus finibus justo quis malesuada eleifend. Nunc molestie efficitur lorem, eget dictum sem vehicula eget. Morbi aliquam, felis nec maximus rhonc"
--      );